### PR TITLE
Visual Studio 2017 RC compatibility

### PR DESCRIPTION
**Pull request by haraldnagel**
- Migrate project to ASP.NET Core 1.1
- Migrate project to MSBuild/`.csproj` for VS2017RC compatibility

### CODE REVIEW

**Comment by haraldnagel** [comment]
@napalm684 I'm not sure that you'll want to merge this but I thought this was the easiest way to send you this branch. It loads in VS2017RC for me and builds. I can't seem to run it due to missing configuration files. Thought it might help as you try to sort out VS2017RC.

On a side note - on our VS Core project we migrated to Core 1.1 but we're not pushing for the MSBuild/`.csproj` migration yet due to some missing tooling (e.g. all the EF commandline stuff seems to still need a `project.json` file to function).

**Comment by napalm684** [comment]
I'll have to check this out for sure not sure why it seems to have went smooth for you and not myself.  Wondering if something on an install failed honestly.  I'll let you know what I find out when I try this thank you for doing that!

**Comment by napalm684** [comment]
I am a bit baffeled as to what I missed as it is working on my machine.  Did you have to make any different alterations to project.json files (other than what was described on the dotnet/cli issue)?  I assume you followed the same steps but when I attempted that I had no luck so I am curious what might have been different.  Thanks again though I will probably merge this in.

**Comment by haraldnagel** [comment]
The only weird thing is I had to do a package restore a couple times. Getting to .NET Core 1.1 in VS2015 didn't raise any issues but then for the migration process to VS2017RC I had to:
1. remove all the `.xproj` projects from the solution
2. add the `.csproj` files to the solution
3. execute a `Package-Restore` in the Package Manager Console

At this point it was complaining about the .NET Framework v4.0 not being included in the project which is weird since it's a Core project and shouldn't be talking about the regular .NET Framework at all?

4. exited VS and then did a `dotnet restore` and a `dotnet nuget restore` 

I think it was at that point where VS2017RC opened it and built without complaining.

**Comment by napalm684** [comment]
Thanks for the help @haraldnagel .  I went through the commits and it was indeed some project.json issues that were preventing a proper migration.  I went ahead and followed the steps more or less that you outlined and was able to reproduce the result.  I branched to rc2017 post migration since you mentioned the EF tools are not caught up yet.

**Pull request closed without merging**
